#!/usr/bin/env python3
"""Linux port of scripts/embed-gen.ps1: regenerate the >>>EMBED section of
compiler/zc.zeph from compiler/runtime.zeph and lib/std/*.zeph."""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
NL = '\n'

def escape(line):
    return line.replace('\\', '\\\\').replace('"', '\\"').replace('{', '\\{').replace('}', '\\}')

def emit(name, path):
    text = path.read_text(encoding='utf-8').replace('\r', '')
    out = [f'fn {name}() -> str {{', '    var sourceLines: [str] = []']
    out += ['    sourceLines.push("' + escape(line) + '\\n")' for line in text.split('\n')]
    out += ['    return sourceLines.join()', '}']
    return NL.join(out) + NL

def main():
    zc = ROOT / 'compiler' / 'zc.zeph'
    std = sorted((ROOT / 'lib' / 'std').glob('*.zeph'), key=lambda p: p.name)
    g = ['// >>>EMBED (generated by scripts/embed-gen.ps1 -- do not edit by hand)' + NL]
    g.append(emit('embeddedRuntimeText', ROOT / 'compiler' / 'runtime.zeph'))
    g.append('fn embeddedRuntimeSource() -> str { return embeddedRuntimeText() }' + NL)
    g.append(f'fn embeddedLibraryCount() -> int {{ return {len(std)} }}' + NL)
    names = ['fn embeddedLibraryName(index: int) -> str {' + NL]
    sources = ['fn embeddedLibrarySource(index: int) -> str {' + NL]
    for i, f in enumerate(std):
        g.append(emit(f'embeddedLibraryText{i}', f))
        names.append(f'    if index == {i} {{ return "std/{f.name}" }}' + NL)
        sources.append(f'    if index == {i} {{ return embeddedLibraryText{i}() }}' + NL)
    names += ['    return ""' + NL, '}' + NL]
    sources += ['    return ""' + NL, '}' + NL]
    g += names + sources + ['// <<<EMBED']
    src = zc.read_text(encoding='utf-8')
    start, end = src.find('// >>>EMBED'), src.find('// <<<EMBED')
    if start < 0 or end < start:
        sys.exit('EMBED markers not found in compiler/zc.zeph')
    out = src[:start] + ''.join(g) + src[end + len('// <<<EMBED'):]
    if '--check' in sys.argv:
        sys.exit(0 if out == src else 'EMBED section is stale')
    zc.write_text(out, encoding='utf-8')
    print('embedded runtime.zeph + std [' + ', '.join(f.name for f in std) + '] into compiler/zc.zeph')

if __name__ == '__main__':
    main()
