"""Aggregate M7 run records into the report the protocol asks for.

The evaluation document is specific about what a report contains: "report
every seed, mean/std, NLL, accuracy, bins, parameter count, processed
examples, wall time, throughput and memory", with "chance and
solver-ceiling" alongside, and it insists that measurement and
interpretation stay separate. This script produces the measurement half and
nothing else. It contains no sentence about what any number means, because
the moment a table generator starts explaining results it starts choosing
which ones to explain.

It also refuses to hide anything. Runs that failed are listed with their
status and error. Families with fewer seeds than requested are marked. A
metric that was not measured prints as "n/a" and never as zero -- the run
records use JSON null for that, per the schema, and a null silently
rendered as 0.0 is the single easiest way to publish a wrong number.

Usage:
    python tools/ml_reference/m7_report.py [--runs runs/m7] [--out RESULTS_M7.md]
"""
from __future__ import annotations

import argparse
import json
import math
import pathlib
import statistics
import sys
from collections import defaultdict

FAMILY_ORDER = [
    "phase", "incoherent", "realrot",
    "gru_state", "gru_param", "gru_quad", "transformer",
    "k0", "k1", "k4", "k8",
]
FAMILY_LABEL = {
    "phase": "phase reasoner (K=2)",
    "incoherent": "ablation: incoherent readout",
    "realrot": "ablation: real rotations",
    "gru_state": "GRU, state-size matched",
    "gru_param": "GRU, parameter matched",
    "gru_quad": "GRU, quadratic head",
    "transformer": "causal Transformer",
    "k0": "phase, K=0", "k1": "phase, K=1", "k4": "phase, K=4", "k8": "phase, K=8",
}


def fmt(v, digits=4):
    """Render a number, or 'n/a' for a missing one. Never renders null as 0."""
    if v is None:
        return "n/a"
    if isinstance(v, float) and (math.isnan(v) or math.isinf(v)):
        return "n/a"
    # -1 is the sentinel m7_run writes for a split it deliberately did not read
    if isinstance(v, (int, float)) and v == -1:
        return "not read"
    return f"{v:.{digits}f}" if isinstance(v, float) else str(v)


def mean_std(xs):
    xs = [x for x in xs if x is not None and x != -1]
    if not xs:
        return None, None
    if len(xs) == 1:
        return xs[0], None
    return statistics.mean(xs), statistics.stdev(xs)


def load(runs_dir: pathlib.Path):
    records, broken = [], []
    for p in sorted(runs_dir.glob("*.json")):
        try:
            records.append((p.name, json.loads(p.read_text())))
        except json.JSONDecodeError as exc:
            broken.append((p.name, str(exc)))
    return records, broken


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", default="runs/m7")
    ap.add_argument("--out", default="RESULTS_M7.md")
    args = ap.parse_args()

    runs_dir = pathlib.Path(args.runs)
    if not runs_dir.is_dir():
        print(f"{runs_dir} does not exist. Run scripts\\m7-sweep.ps1 first.", file=sys.stderr)
        return 1

    records, broken = load(runs_dir)
    if not records:
        print(f"no run records in {runs_dir}", file=sys.stderr)
        return 1

    completed = [(n, r) for n, r in records if r.get("status") == "completed"]
    failed = [(n, r) for n, r in records if r.get("status") != "completed"]
    smoke = [(n, r) for n, r in completed if r.get("smoke")]
    real = [(n, r) for n, r in completed if not r.get("smoke")]

    out = []
    w = out.append
    w("# M7 measurements\n")
    w("Generated by `tools/ml_reference/m7_report.py` from the run records in "
      f"`{runs_dir.as_posix()}`. This file is measurement only. Interpretation belongs in "
      "RESULTS.md, under its own heading, and no claim about mechanism, superiority, "
      "quantum behaviour or cognition follows from anything here.\n")

    w(f"- run records found: {len(records)}")
    w(f"- completed: {len(completed)} ({len(real)} full, {len(smoke)} smoke-only)")
    w(f"- not completed: {len(failed)}")
    if broken:
        w(f"- unreadable record files: {len(broken)}")
    w("")

    # The budget is read back out of the records rather than restated here, so
    # the report cannot describe a budget different from the one that ran.
    budgets = {
        (r.get("preset"), r.get("optimizer_steps"), r.get("batch"), r.get("weight_decay"),
         r.get("selection_rows"), r.get("test_rows"))
        for _, r in completed
    }
    w("## Declared budget, as recorded in the runs\n")
    if len(budgets) == 1:
        preset, steps, batch, wd, selrows, testrows = budgets.pop()
        w(f"preset `{preset}`, {steps} optimizer steps, batch {batch}, weight decay {wd}, "
          f"{selrows} validation rows for selection, {testrows} rows of each frozen split at the end.\n")
    else:
        w("**The runs do not share one budget.** They are not comparable as a single "
          "experiment. Distinct budgets found:\n")
        for b in sorted(budgets, key=str):
            w(f"- preset={b[0]} steps={b[1]} batch={b[2]} wd={b[3]} sel={b[4]} test={b[5]}")
        w("")

    by_family = defaultdict(lambda: defaultdict(list))
    for _, r in real:
        by_family[r.get("task")][r.get("family")].append(r)

    for task in sorted(by_family):
        w(f"## Task {task.upper()}\n")
        chance = next((r.get("chance_accuracy") for r in
                       [x for fam in by_family[task].values() for x in fam]), None)
        w(f"Chance accuracy: {fmt(chance)}. The symbolic solver's ceiling is 1.0 by "
          "construction: both task generators are built from a solver that recovers the "
          "label from the token sequence alone, which is what A30 verified.\n")
        w("| family | seeds | params | val acc | val NLL | composition acc | length acc | s/run | ex/s |")
        w("|---|---|---|---|---|---|---|---|---|")
        for fam in FAMILY_ORDER:
            rs = by_family[task].get(fam)
            if not rs:
                continue
            acc_m, acc_s = mean_std([r.get("validation_accuracy") for r in rs])
            nll_m, nll_s = mean_std([r.get("validation_nll") for r in rs])
            cmp_m, _ = mean_std([r.get("composition_accuracy") for r in rs])
            len_m, _ = mean_std([r.get("length_accuracy") for r in rs])
            sec_m, _ = mean_std([r.get("elapsed_seconds") for r in rs])
            thr_m, _ = mean_std([r.get("throughput_examples_per_second") for r in rs])
            params = rs[0].get("parameters_real")
            seeds = sorted({r.get("seed") for r in rs})
            seedtxt = ",".join(str(s) for s in seeds)
            if len(seeds) < 3:
                seedtxt += " (fewer than 3)"
            acc = fmt(acc_m) + (f" ± {fmt(acc_s)}" if acc_s is not None else "")
            nll = fmt(nll_m) + (f" ± {fmt(nll_s)}" if nll_s is not None else "")
            w(f"| {FAMILY_LABEL.get(fam, fam)} | {seedtxt} | {params} | {acc} | {nll} | "
              f"{fmt(cmp_m)} | {fmt(len_m)} | {fmt(sec_m, 1)} | {fmt(thr_m, 1)} |")
        w("")

        w("### Every seed, unaggregated\n")
        w("| family | seed | lr | selected step | val acc | val NLL | composition | length |")
        w("|---|---|---|---|---|---|---|---|")
        for fam in FAMILY_ORDER:
            for r in sorted(by_family[task].get(fam, []), key=lambda x: (x.get("seed", 0))):
                w(f"| {fam} | {r.get('seed')} | {fmt(r.get('learning_rate'), 5)} | "
                  f"{r.get('selected_step')} | {fmt(r.get('validation_accuracy'))} | "
                  f"{fmt(r.get('validation_nll'))} | {fmt(r.get('composition_accuracy'))} | "
                  f"{fmt(r.get('length_accuracy'))} |")
        w("")

        w("### Matching, as achieved rather than as intended\n")
        for fam in FAMILY_ORDER:
            rs = by_family[task].get(fam)
            if rs and rs[0].get("match_note"):
                w(f"- {FAMILY_LABEL.get(fam, fam)}: {rs[0]['match_note']}")
        w("")

    if smoke:
        w("## Smoke runs, excluded from every table above\n")
        w("These evaluated validation only and never read the frozen splits.\n")
        for n, r in smoke:
            w(f"- `{n}`: {r.get('family')} task {r.get('task')} seed {r.get('seed')}, "
              f"val acc {fmt(r.get('validation_accuracy'))}")
        w("")

    w("## Failures and incomplete runs\n")
    if not failed and not broken:
        w("None. Every planned run produced a completed record.\n")
    else:
        for n, r in failed:
            w(f"- `{n}`: status `{r.get('status')}`, error `{r.get('error')}`")
        for n, e in broken:
            w(f"- `{n}`: unreadable, {e}")
        w("")

    w("## Memory\n")
    w("`peak_live_bytes` and `peak_reserved_bytes` are null in every record and print as "
      "n/a rather than 0. The runtime does not expose an allocator high-water counter to "
      "programs, so the number is not available; it is left missing rather than "
      "substituted.\n")

    text = "\n".join(out) + "\n"
    pathlib.Path(args.out).write_text(text, encoding="utf-8")
    print(f"wrote {args.out}: {len(completed)} completed runs, {len(failed)} not completed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
