#!/usr/bin/env python3
"""Random Zephyr programs over floats, closures and interfaces (Q10), for
two-way differential testing (baseline vs -O2). Side-effect free: called
functions never write globals, so results can't depend on evaluation order and
any mismatch is a miscompile. Floats stay bounded, and are folded into the
checksum through `(x * 1000.0) as int` after clamping, so no conversion
overflows.
Usage: genext.py SEED > program.zeph
"""
import random, sys

def program(seed):
    r = random.Random(seed)
    L = ['// generated by research/fuzz/genext.py',
         'interface Op {', '    fn run(self, x: float) -> float', '    fn tag(self) -> int', '}',
         'struct Scale { k: float }', 'impl Scale {', '    fn run(self, x: float) -> float { return x * self.k }', '    fn tag(self) -> int { return 1 }', '}',
         'struct Shift { d: float }', 'impl Shift {', '    fn run(self, x: float) -> float { return x + self.d }', '    fn tag(self) -> int { return 2 }', '}',
         'struct Clip { lo: float, hi: float }', 'impl Clip {',
         '    fn run(self, x: float) -> float {', '        if x < self.lo { return self.lo }', '        if x > self.hi { return self.hi }', '        return x', '    }',
         '    fn tag(self) -> int { return 3 }', '}',
         'fn clamp(x: float) -> float {', '    if x > 1000000.0 { return 1000000.0 }', '    if x < -1000000.0 { return -1000000.0 }', '    if x != x { return 0.0 }', '    return x', '}',
         'fn fold(acc: int, x: float) -> int { return acc * 31 + (clamp(x) * 1000.0) as int }']
    def fexpr(vars, depth=0):
        if depth > 3 or r.random() < 0.3:
            if vars and r.random() < 0.6: return r.choice(vars)
            return f'{r.randint(-40, 40) / 4}'
        a, b = fexpr(vars, depth + 1), fexpr(vars, depth + 1)
        op = r.choice(['+', '-', '*', 'min', 'max', 'sqrt', 'div', 'if', 'int'])
        if op in ('min', 'max'): return f'{op}({a}, {b})'
        if op == 'sqrt': return f'sqrt(clamp({a}) * clamp({a}))'
        if op == 'div': return f'(clamp({a}) / (clamp({b}) * clamp({b}) + 1.0))'
        if op == 'if': return f'(if {a} < {b} {{ {a} }} else {{ {fexpr(vars, depth + 1)} }})'
        if op == 'int': return f'(((clamp({a}) * 10.0) as int % 97) as float)'
        return f'clamp({a} {op} {b})'
    body = ['    var acc = 0', '    var ops: [Op] = []', '    var fs: [float] = [0.5, 1.5, -2.0]']
    vars = []
    for step in range(r.randint(10, 30)):
        k = r.random()
        if k < 0.25:
            v = f'x{step}'; body.append(f'    let {v} = {fexpr(vars)}'); vars.append(v)
        elif k < 0.4:
            kind = r.randint(0, 2)
            mk = [f'Scale{{k: {fexpr(vars)}}}', f'Shift{{d: {fexpr(vars)}}}', f'Clip{{lo: -{r.randint(1, 9)}.0, hi: {r.randint(1, 9)}.0}}'][kind]
            body.append(f'    ops.push({mk})')
        elif k < 0.55:
            body.append(f'    var y{step} = {fexpr(vars)}')
            body.append(f'    for op in ops {{ y{step} = clamp(op.run(y{step}))\n        acc = acc * 7 + op.tag() }}')
            body.append(f'    acc = fold(acc, y{step})')
        elif k < 0.7:
            c = fexpr(vars)
            body.append(f'    let g{step} = fn(t: float) -> float {{ return clamp(t * {c} + {fexpr(vars)}) }}')
            body.append(f'    acc = fold(acc, g{step}({fexpr(vars)}))')
        elif k < 0.8:
            body.append(f'    fs.push({fexpr(vars)})')
            body.append(f'    var s{step} = 0.0\n    for f in fs {{ s{step} = clamp(s{step} + f * {fexpr(vars)}) }}\n    acc = fold(acc, s{step})')
        elif k < 0.9:
            body.append(f'    for i{step} in 0..{r.randint(1, 9)} {{ acc = fold(acc, clamp({fexpr(vars + [f"(i{step} as float)"])})) }}')
        else:
            body.append(f'    acc = fold(acc, {fexpr(vars)})')
    L.append('fn main() {'); L += body; L.append('    print(acc)'); L.append('}')
    return '\n'.join(L) + '\n'

if __name__ == '__main__':
    print(program(int(sys.argv[1])), end='')
