#!/usr/bin/env python3
"""Random Zephyr programs over maps and generics (Q10), for two-way
differential testing (baseline vs -O2). Side-effect free. Map iteration is
folded order-independently (a sum of per-entry hashes), so the result can't
depend on iteration order.
Usage: genmap.py SEED > program.zeph
"""
import random, sys

def program(seed):
    r = random.Random(seed)
    L = ['// generated by research/fuzz/genmap.py',
         'struct Box[T] { item: T, count: int }',
         'fn pick[T](a: T, b: T, first: bool) -> T {', '    if first { return a }', '    return b', '}',
         'fn boxed[T](x: T, n: int) -> Box[T] { return Box{item: x, count: n} }',
         'fn mix(x: int) -> int { return (x * 1103515245 + 12345) & 1048575 }',
         'fn sumInts(m: [int: int]) -> int {', '    var t = 0', '    for k in m.keys() { t += mix(k * 31 + m[k]) }', '    return t', '}',
         'fn sumStrs(m: [str: int]) -> int {', '    var t = 0', '    for k in m.keys() { t += mix(k.len() * 131 + m[k]) }', '    return t', '}']
    body = ['    var acc = 0', '    var im: [int: int] = [:]', '    var sm: [str: int] = [:]', '    var boxes: [Box[int]] = []', '    var words: [str] = ["x", "yy"]']
    for step in range(r.randint(15, 40)):
        k = r.random()
        if k < 0.2:
            body.append(f'    im[{r.randint(0, 40)}] = im.get({r.randint(0, 40)}).or({r.randint(0, 9)}) + {r.randint(1, 5)}')
        elif k < 0.3:
            body.append(f'    if im.has({r.randint(0, 40)}) {{ im.remove({r.randint(0, 40)}) }}')
        elif k < 0.45:
            body.append(f'    let w{step} = words[{r.randint(0, 9)} % words.len()] + "{r.randint(0, 99)}"')
            body.append(f'    sm[w{step}] = sm.get(w{step}).or(0) + {r.randint(1, 7)}')
            body.append(f'    if {r.randint(0, 3)} == 0 {{ words.push(w{step}) }}')
        elif k < 0.55:
            body.append(f'    acc = acc * 31 + sumInts(im) + sumStrs(sm)')
        elif k < 0.7:
            body.append(f'    boxes.push(boxed(pick({r.randint(0, 99)}, acc & 1023, {r.choice(["true", "false"])}), {r.randint(0, 9)}))')
            body.append(f'    let bs{step} = boxed(pick("a{r.randint(0, 9)}", words[0], acc % 2 == 0), {r.randint(0, 9)})')
            body.append(f'    acc = acc * 7 + bs{step}.item.len() + bs{step}.count')
        elif k < 0.8:
            body.append(f'    var t{step} = 0\n    for b in boxes {{ t{step} = mix(t{step} + b.item * 3 + b.count) }}\n    acc = acc * 13 + t{step}')
        elif k < 0.9:
            body.append(f'    let fm{step}: [int: float] = [{r.randint(0, 5)}: {r.randint(0, 9)}.5, {r.randint(6, 9)}: 2.25]')
            body.append(f'    acc = acc * 3 + (fm{step}.get({r.randint(0, 9)}).or(1.0) * 4.0) as int + fm{step}.len()')
        else:
            body.append(f'    acc = mix(acc + im.len() * 17 + sm.len() + words.len())')
    L.append('fn main() {'); L += body
    L.append('    acc = acc * 31 + sumInts(im) + sumStrs(sm) + boxes.len()')
    L.append('    print(acc)'); L.append('}')
    return '\n'.join(L) + '\n'

if __name__ == '__main__':
    print(program(int(sys.argv[1])), end='')
