#!/usr/bin/env python3
"""Random Zephyr programs aimed at reference-counting and ownership bugs, the
miscompile classes in the -O2 commit history (M15): aliases into lists of
structs, globals replaced while a local still uses the old value, strings
built and sliced, lists of lists, closures capturing lists, maps with string
keys. Deterministic, panic-free, prints a checksum.
Usage: genref.py SEED > program.zeph
"""
import random, sys

def program(seed):
    r = random.Random(seed)
    L = ['// generated by research/fuzz/genref.py',
         'struct Box { n: int, items: [int], name: str }',
         'var boxes: [Box] = []',
         'var names: [str] = ["a", "bb", "ccc"]',
         'var grid: [[int]] = [[1, 2], [3]]',
         'var counts: [str: int] = [:]',
         'var acc = 0',
         'fn mix(x: int) -> int { return (x * 1103515245 + 12345) & 1048575 }',
         'fn total(b: Box) -> int {',
         '    var t = b.n + b.name.len()',
         '    for x in b.items { t = t * 3 + x }',
         '    return t',
         '}',
         'fn touch(b: Box, k: int) {',
         '    b.items.push(k)',
         '    b.n = b.n + k',
         '}']
    body = []
    def pick(n): return r.randint(0, n)
    def ix(lst): return f'(({lst}.len() + {pick(9)}) % {lst}.len())'
    for step in range(r.randint(15, 45)):
        k = r.random()
        if k < 0.12:
            body.append(f'boxes.push(Box{{n: {pick(99)}, items: [{pick(9)}, {pick(9)}], name: names[{ix("names")}] + "{pick(9)}"}})')
        elif k < 0.22:
            body.append(f'if boxes.len() > 0 {{ let b = boxes[{ix("boxes")}]\n        touch(b, {pick(50)})\n        acc = acc * 31 + total(b) }}')
        elif k < 0.30:
            body.append(f'if boxes.len() > 1 {{ let keep = boxes[0]\n        boxes[{ix("boxes")}] = Box{{n: {pick(9)}, items: [], name: "r"}}\n        acc = acc * 7 + total(keep) }}')
        elif k < 0.38:
            body.append(f'let old{step} = names\n    names = [names[{ix("names")}] + "x", "y{pick(9)}"]\n    acc = acc * 5 + old{step}.len() + names[0].len()')
        elif k < 0.46:
            body.append(f'let row{step} = grid[{ix("grid")}]\n    grid.push([{pick(9)}, {pick(9)}, {pick(9)}])\n    row{step}.push({pick(9)})\n    acc = acc * 3 + row{step}.len() + grid.len()')
        elif k < 0.54:
            body.append(f'let word{step} = names[{ix("names")}] + "-" + "{pick(999)}"\n    counts[word{step}] = counts.get(word{step}).or(0) + {pick(5)}\n    acc = acc + counts.len()')
        elif k < 0.62:
            body.append(f'let captured{step} = grid[{ix("grid")}]\n    let f{step} = fn(x: int) -> int {{ return x + captured{step}.len() }}\n    acc = f{step}(acc) & 1048575')
        elif k < 0.70:
            body.append(f'let text{step} = "{{acc}}:{{names.len()}}:" + names[{ix("names")}]\n    acc = acc * 11 + text{step}.sub(0, min(text{step}.len(), {pick(6) + 1})).len()')
        elif k < 0.78:
            body.append(f'if boxes.len() > 0 {{ var first = boxes[0]\n        first = Box{{n: first.n + 1, items: first.items, name: first.name}}\n        first.items.push({pick(9)})\n        acc = acc * 13 + total(boxes[0]) + total(first) }}')
        elif k < 0.86:
            body.append(f'for i{step} in 0..{pick(5) + 1} {{ acc = mix(acc + i{step})\n        if acc % 3 == 0 and boxes.len() > 0 {{ boxes.pop() }} }}')
        elif k < 0.93:
            body.append(f'let copy{step} = grid\n    grid = [[{pick(9)}]]\n    acc = acc * 17 + copy{step}.len() + grid[0][0]')
        else:
            body.append(f'var s{step} = ""\n    for j{step} in 0..{pick(6)} {{ s{step} += names[j{step} % names.len()] }}\n    acc = acc * 19 + s{step}.len()')
    L.append('fn main() {')
    for b in body: L.append('    ' + b)
    L.append('    acc = acc * 23 + boxes.len() + counts.len()')
    L.append('    for b in boxes { acc = mix(acc + total(b)) }')
    L.append('    for row in grid { acc = mix(acc + row.len()) }')
    L.append('    for n in names { acc = mix(acc + n.len()) }')
    L.append('    print(acc)')
    L.append('}')
    return '\n'.join(L) + '\n'

if __name__ == '__main__':
    print(program(int(sys.argv[1])), end='')
