# scripts/embed-gen.ps1 - regenerate the embedded-sources section of compiler/zc.zeph
# from compiler/runtime.zeph and lib/std/*.zeph, so a lone zc.exe carries its own runtime and
# standard library. Run automatically by selfbuild.ps1; run by hand after editing
# runtime.zeph or std/ if you build some other way.
$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot
$zc = Join-Path $root "compiler\zc.zeph"

$utf8 = New-Object System.Text.UTF8Encoding($false)

# escape one source line into a Zephyr string literal body
function EscapeLine([string]$line) {
    $line = $line.Replace("\", "\\").Replace('"', '\"').Replace("{", "\{").Replace("}", "\}")
    return $line
}

# emit a function that rebuilds one file's text: a push per source line + join
function EmitFileFunction([string]$functionName, [string]$path) {
    $text = [System.IO.File]::ReadAllText($path, $utf8) -replace "`r", ""
    $lines = $text -split "`n"
    $builder = New-Object System.Text.StringBuilder
    [void]$builder.AppendLine("fn $functionName() -> str {")
    [void]$builder.AppendLine('    var sourceLines: [str] = []')
    foreach ($line in $lines) {
        [void]$builder.AppendLine('    sourceLines.push("' + (EscapeLine $line) + '\n")')
    }
    [void]$builder.AppendLine("    return sourceLines.join()")
    [void]$builder.AppendLine("}")
    return $builder.ToString()
}

# the std library files, in a stable order, named as they are imported
$stdFiles = @(Get-ChildItem (Join-Path $root "lib\std\*.zeph") | Sort-Object Name)

$generated = New-Object System.Text.StringBuilder
[void]$generated.AppendLine("// >>>EMBED (generated by scripts/embed-gen.ps1 -- do not edit by hand)")
[void]$generated.Append((EmitFileFunction "embeddedRuntimeText" (Join-Path (Join-Path $root "compiler") "runtime.zeph")))
[void]$generated.AppendLine("fn embeddedRuntimeSource() -> str { return embeddedRuntimeText() }")
[void]$generated.AppendLine("fn embeddedLibraryCount() -> int { return $($stdFiles.Count) }")

$nameFunction = New-Object System.Text.StringBuilder
[void]$nameFunction.AppendLine("fn embeddedLibraryName(index: int) -> str {")
$sourceFunction = New-Object System.Text.StringBuilder
[void]$sourceFunction.AppendLine("fn embeddedLibrarySource(index: int) -> str {")
for ($i = 0; $i -lt $stdFiles.Count; $i++) {
    $file = $stdFiles[$i]
    [void]$generated.Append((EmitFileFunction "embeddedLibraryText$i" $file.FullName))
    [void]$nameFunction.AppendLine("    if index == $i { return `"std/$($file.Name)`" }")
    [void]$sourceFunction.AppendLine("    if index == $i { return embeddedLibraryText$i() }")
}
[void]$nameFunction.AppendLine('    return ""')
[void]$nameFunction.AppendLine("}")
[void]$sourceFunction.AppendLine('    return ""')
[void]$sourceFunction.AppendLine("}")
[void]$generated.Append($nameFunction.ToString())
[void]$generated.Append($sourceFunction.ToString())
[void]$generated.Append("// <<<EMBED")

# splice into zc.zeph between the markers
$source = [System.IO.File]::ReadAllText($zc, $utf8)
$start = $source.IndexOf("// >>>EMBED")
$endMark = "// <<<EMBED"
$end = $source.IndexOf($endMark)
if ($start -lt 0 -or $end -lt 0 -or $end -lt $start) {
    Write-Host "EMBED markers not found in compiler\zc.zeph" -ForegroundColor Red
    exit 1
}
$output = $source.Substring(0, $start) + $generated.ToString() + $source.Substring($end + $endMark.Length)
[System.IO.File]::WriteAllText($zc, $output, $utf8)

$fileNames = ($stdFiles | ForEach-Object { $_.Name }) -join ", "
Write-Host "embedded runtime.zeph + std [$fileNames] into compiler\zc.zeph"
