# tools/embed-gen.ps1 - regenerate the embedded-sources section of selfhost/zc.zeph
# from runtime.zeph and std/*.zeph, so a lone zc.exe carries its own runtime and
# standard library. Run automatically by selfbuild.ps1; run by hand after editing
# runtime.zeph or std/ if you build some other way.
$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot
$zc = Join-Path $root "compiler\zc.zeph"

$utf8 = New-Object System.Text.UTF8Encoding($false)

# escape one source line into a Zephyr string literal body
function EscapeLine([string]$s) {
    $s = $s.Replace("\", "\\").Replace('"', '\"').Replace("{", "\{").Replace("}", "\}")
    return $s
}

# emit a function that rebuilds one file's text: a push per source line + join
function EmitFileFn([string]$fnname, [string]$path) {
    $text = [System.IO.File]::ReadAllText($path, $utf8) -replace "`r", ""
    $lines = $text -split "`n"
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine("fn $fnname() -> str {")
    [void]$sb.AppendLine('    var p: [str] = []')
    foreach ($ln in $lines) {
        [void]$sb.AppendLine('    p.push("' + (EscapeLine $ln) + '\n")')
    }
    [void]$sb.AppendLine("    return p.join()")
    [void]$sb.AppendLine("}")
    return $sb.ToString()
}

# the std library files, in a stable order, named as they are imported
$stdFiles = @(Get-ChildItem (Join-Path $root "lib\std\*.zeph") | Sort-Object Name)

$gen = New-Object System.Text.StringBuilder
[void]$gen.AppendLine("// >>>EMBED (generated by tools/embed-gen.ps1 -- do not edit by hand)")
[void]$gen.Append((EmitFileFn "__emb_rt" (Join-Path (Join-Path $root "compiler") "runtime.zeph")))
[void]$gen.AppendLine("fn embedded_runtime() -> str { return __emb_rt() }")
[void]$gen.AppendLine("fn embedded_count() -> int { return $($stdFiles.Count) }")

$nameFn = New-Object System.Text.StringBuilder
[void]$nameFn.AppendLine("fn embedded_name(i: int) -> str {")
$srcFn = New-Object System.Text.StringBuilder
[void]$srcFn.AppendLine("fn embedded_src(i: int) -> str {")
for ($i = 0; $i -lt $stdFiles.Count; $i++) {
    $f = $stdFiles[$i]
    [void]$gen.Append((EmitFileFn "__emb_$i" $f.FullName))
    [void]$nameFn.AppendLine("    if i == $i { return `"std/$($f.Name)`" }")
    [void]$srcFn.AppendLine("    if i == $i { return __emb_$i() }")
}
[void]$nameFn.AppendLine('    return ""')
[void]$nameFn.AppendLine("}")
[void]$srcFn.AppendLine('    return ""')
[void]$srcFn.AppendLine("}")
[void]$gen.Append($nameFn.ToString())
[void]$gen.Append($srcFn.ToString())
[void]$gen.Append("// <<<EMBED")

# splice into zc.zeph between the markers
$src = [System.IO.File]::ReadAllText($zc, $utf8)
$start = $src.IndexOf("// >>>EMBED")
$endMark = "// <<<EMBED"
$end = $src.IndexOf($endMark)
if ($start -lt 0 -or $end -lt 0 -or $end -lt $start) {
    Write-Host "EMBED markers not found in compiler\zc.zeph" -ForegroundColor Red
    exit 1
}
$out = $src.Substring(0, $start) + $gen.ToString() + $src.Substring($end + $endMark.Length)
[System.IO.File]::WriteAllText($zc, $out, $utf8)

$n = ($stdFiles | ForEach-Object { $_.Name }) -join ", "
Write-Host "embedded runtime.zeph + std [$n] into compiler\zc.zeph"
