"""Regenerate compiler/zc.zeph's embedded runtime and standard library."""

import argparse
from pathlib import Path


def emit_file_function(function_name, path):
    """Emit one push per source line, including a final empty source line."""
    text = path.read_bytes().decode("utf-8-sig").replace("\r", "")
    lines = [f"fn {function_name}() -> str {{", "    var sourceLines: [str] = []"]
    for line in text.split("\n"):
        escaped = line.replace("\\", "\\\\").replace('"', '\\"').replace("{", "\\{").replace("}", "\\}")
        lines.append('    sourceLines.push("' + escaped + '\\n")')
    lines.extend(["    return sourceLines.join()", "}"])
    return "\n".join(lines) + "\n"


def main():
    """Replace only the EMBED section, or check that it is already current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="check generated sources without writing")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    zc = root / "compiler" / "zc.zeph"
    std_files = sorted(
        (root / "lib" / "std").glob("*.zeph"),
        key=lambda path: path.name.casefold(),
    )
    generated = [
        "// >>>EMBED (generated by scripts/embed-gen.ps1 -- do not edit by hand)\n",
        emit_file_function("embeddedRuntimeText", root / "compiler" / "runtime.zeph"),
        "fn embeddedRuntimeSource() -> str { return embeddedRuntimeText() }\n",
        f"fn embeddedLibraryCount() -> int {{ return {len(std_files)} }}\n",
    ]
    names = ["fn embeddedLibraryName(index: int) -> str {"]
    sources = ["fn embeddedLibrarySource(index: int) -> str {"]
    for index, path in enumerate(std_files):
        generated.append(emit_file_function(f"embeddedLibraryText{index}", path))
        names.append(f'    if index == {index} {{ return "std/{path.name}" }}')
        sources.append(f"    if index == {index} {{ return embeddedLibraryText{index}() }}")
    for function in (names, sources):
        function.extend(['    return ""', "}"])
        generated.append("\n".join(function) + "\n")
    end_mark = "// <<<EMBED"
    generated.append(end_mark)

    source = zc.read_bytes().decode("utf-8")
    start = source.find("// >>>EMBED")
    end = source.find(end_mark)
    if start < 0 or end < start:
        parser.exit(1, "EMBED markers not found in compiler/zc.zeph\n")
    section = "".join(generated)
    output = source[:start] + section + source[end + len(end_mark):]
    if args.check:
        # Git may check out generated lines as CRLF; their contents are unchanged.
        if source[start:end + len(end_mark)].replace("\r", "") != section:
            parser.exit(1, "embedded sources are stale; run python scripts/embed-gen.py\n")
        print("embedded sources are current")
    else:
        zc.write_bytes(output.encode("utf-8"))
        file_names = ", ".join(path.name for path in std_files)
        print(f"embedded runtime.zeph + std [{file_names}] into compiler/zc.zeph")


if __name__ == "__main__":
    main()
